name: liedetector
adopt-info: liedetector
summary: A Python-based Lie Detector
description: |
  Your terminal knows the truth.

license: MIT

base: core18
grade: stable 
confinement: strict

apps:
  liedetector:
    command: python3 $SNAP/bin/liedetector.py

parts: 
  liedetector:
    source: https://github.com/kz6fittycent/lie_detector
    source-type: git
    plugin: python
    python-version: python3
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    
    build-packages:
      - python3
     
    stage-packages:
      - python3
  
  publish:
    plugin: dump
    source: .
    organize:
      ./liedetector.py: bin/liedetector.py
